name = "reflection-bench"
defaultTargets = ["ReflectionBench"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "lean-pr-testing-5563"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries.git"
rev = "nightly-testing"

[[require]]
name = "lean4lean"
git = "https://github.com/nomeata/lean4lean.git"

[[lean_lib]]
name = "ReflectionBench"
precompileModules = true

[[lean_exe]]
name = "reflection-bench"
root = "ReflectionBench.BenchOLean"
supportInterpreter = true

[[lean_lib]]
name = "Test"
